
#批量创建pvc：enabled为true时创建
persistence:
  enabled: true
  pvc:
  - name: qloudmariadb-data
    size: 3Gi
  - name: qloudmariadb-binlog
    size: 3Gi
  annotations:
    volume.beta.kubernetes.io/storage-class: ssd
    volume.beta.kubernetes.io/storage-provisioner: flexvolume-huawei.com/fuxivol
  labels:
    failure-domain.beta.kubernetes.io/region: cn-north-1
    failure-domain.beta.kubernetes.io/zone: cn-north-1a
