{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- range $zkIndex,$map :=  .Values.volume }}
{{- if eq  "gluster" ($map.type) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Values.service.annotations.name }}-{{ $map.name }}
{{- if $.Values.persistence.annotations }}
  annotations:
{{ toYaml $.Values.persistence.annotations | indent 4 }}
{{- end }}
{{- if $.Values.persistence.labels }}
  labels:
{{ toYaml $.Values.persistence.labels | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $map.volumesize }}
---
{{- end }}
{{- end }}
{{- end }}

      
 
