apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambssador
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30009
  selector:
    service: ambassador
