apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
