{{- if .Values.ingressEnabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "common.fullname" . }}
  annotations:
{{ toYaml .Values.ingressAnnotations | indent 4 }}
  labels:
{{- if .Values.ingressLabels }}
{{ toYaml .Values.ingressLabels | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range $i,$map :=  .Values.ingressHosts }}    
  {{- if and $.Values.ingressAddns (not (eq $.Release.Namespace "default") ) }}
  - host: {{ $map.host }}.{{ $.Release.Namespace }}.{{ $map.domain }}
  {{- else }}
  - host: {{ $map.host }}.{{ $map.domain }}
  {{- end }}
    http:
      paths:
      {{- range $i,$list :=  $map.paths }}
      - path: {{ $list.path }}
        backend:
          serviceName: {{ $.Values.serviceName }}
          servicePort: {{ $list.servicePort }}
      {{- end -}}
  {{- end -}}
  {{- if .Values.ingressTls }}
  tls:
  {{- range $i,$map :=  .Values.ingressTls }}
  - secretName: {{ $map.secretName }}
    hosts:
    {{- range $j,$map2 :=  $map.hosts }}
    {{- if and $.Values.ingressAddns (not (eq $.Release.Namespace "default") ) }}
    - {{ $map2.host }}.{{ $.Release.Namespace }}.{{ $map2.domain }}
    {{- else }}
    - {{ $map2.host }}.{{ $map2.domain }}
    {{- end }}
    {{- end }}
  {{- end -}}
  {{- end -}}
{{- end -}}
