{{- if .Values.envsecretEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-envsecret
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $i,$map :=  .Values.envsecretData }}
  {{ $map.key }}: {{ $map.value | b64enc | quote }}
  {{- end -}}
{{- end -}}
