{{- if .Values.envsecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.annotations.name }}-envsecret
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $i,$map :=  .Values.envsecret.data }}
  {{ $map.key }}: {{ $map.value | b64enc | quote }}
  {{- end -}}
{{- end -}}
