apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: solo
  namespace: paas
spec:
  secretName: paas-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h
  renewBefore: 360h
  # keyEncoding: pkcs1
  dnsNames:
  - web.k8s.com