apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mynginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: mynginx
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mynginx
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mynginx
    spec:
      containers:
      - image: nginx
        name: mynginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: paas
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - web.k8s.com
    secretName: paas-tls
  rules:
  - host: web.k8s.com
    http:
      paths:
      - backend:
          serviceName: mynginx
          servicePort: 80